//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>GalleryImages</summary>
	[PublishedContentModel("galleryImages")]
	public partial class GalleryImages : PublishedContentModel, IFolder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "galleryImages";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public GalleryImages(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GalleryImages, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// height
		///</summary>
		[ImplementPropertyType("height")]
		public string Height
		{
			get { return this.GetPropertyValue<string>("height"); }
		}

		///<summary>
		/// ImageDescription
		///</summary>
		[ImplementPropertyType("imageDescription")]
		public IHtmlString ImageDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("imageDescription"); }
		}

		///<summary>
		/// bytes
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Extension
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// PickImage
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public IPublishedContent UmbracoFile
		{
			get { return this.GetPropertyValue<IPublishedContent>("umbracoFile"); }
		}

		///<summary>
		/// width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return Umbraco.Web.PublishedContentModels.Folder.GetContents(this); }
		}
	}
}
